language: go
go:
            - 1.9
            - 1.10
            - master
os:
            - linux
            - osx
before_script:                 
            - make dep-install
            - make dep
            - make 
script:
            - ./bin/zsh-logger --version
